name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Composer install all need packages
        run: composer install
      
      - name: Validate composer.json and composer.lock
        run: composer validate --strict
      
      - name: Run unit tests
        run: composer run test
